### ISSUE TITLE
emergency banner needed TODAY

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/global_alerts#31]
Banner should start now. 

Text: Due to the widespread power outage, Stanford Libraries will close at 5pm on Tuesday 6/21/2022. Hours may be affected Wednesday 6/22/2022. Please check back for updates.

We may need updates early tomorrow morning.

**Comment by anarchivist** [comment]
fixed by #32; awaiting app restart

**Comment by tallenaz** [comment]
apache was restarted on sw-webapp-a/b/c/d/e, mylibrary-prod-a/b, sul-library-hours-prod, and sul-bento-prod-a/b per
https://sul.app.opsgenie.com/alert/detail/6e86fe45-0ab8-4f1c-bf52-5cef8eba6426-1655858258059/details
