### ISSUE TITLE
Winter Break 22-23 alert

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/global_alerts#40]
Schedule to appear: Mon. 12/19/22 through Tues. 1/3/23

Text: “The Stanford Libraries will be operating on a reduced schedule during the Stanford Winter Closure period (Wednesday, December 21, 2022 - Tuesday, January 3, 2023). More information about <a href=”https://library-hours.stanford.edu/”>hours</a>

Applications: SW, MyLibrary, Bento

**Comment by jcoyne** [comment]
@saseestone Surely you mean 2022 (not 2002), right?

**Comment by saseestone** [comment]
ugh. Yes, I do mean 2022. Thanks for catching that.
