### ISSUE TITLE
Add global alert about ILS migration

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/global_alerts#49]
### For Searchworks:
Stanford Libraries will be undergoing a major system upgrade Saturday, August 19 through Sunday, August 27. 

During the upgrade, libraries will be open [regular hours](https://library-hours.stanford.edu/) and eligible materials may be checked out. Item status and availability information may not be up to date. Requests can be submitted, but materials may not be ready for use until after August 31. My Library Account will not be available during the upgrade. [More information](https://library.stanford.edu/news/major-system-upgrade-august-19-27) 

### For MyLibrary
A major system upgrade will occur Saturday, August 19 through Sunday, August 27. My Library Account will not be available during this period.

Libraries will be open [regular hours](https://library-hours.stanford.edu/) and eligible materials may be checked out. [SearchWorks](https://searchworks.stanford.edu/) will be available, but item status and availability information may not be up to date. Requests can be submitted, but materials may not be ready for use until after August 31. [More information](https://library.stanford.edu/news/major-system-upgrade-august-19-27)

### For Bento
Stanford Libraries will be undergoing a major system upgrade Saturday, August 19 through Sunday, August 27. 

During the upgrade, libraries will be open [regular hours](https://library-hours.stanford.edu/) and eligible materials may be checked out. [SearchWorks](https://searchworks.stanford.edu/) will be available, but item status and availability information may not be up to date. Requests can be submitted, but materials may not be ready for use until after August 31. My Library Account will not be available during the upgrade. [More information](https://library.stanford.edu/news/major-system-upgrade-august-19-27)

### For Searchworks
Stanford Libraries is undergoing a major system upgrade. 

Libraries are open [regular hours](https://library-hours.stanford.edu/) and eligible materials may be checked out. Item status and availability information may not be up to date. Requests can be submitted, but materials may not be ready for use until after August 31. My Library Account is unavailable until August 28. [More information](https://library.stanford.edu/news/major-system-upgrade-august-19-27)

### For Bento
Stanford Libraries is undergoing a major system upgrade. 

Libraries are open [regular hours](https://library-hours.stanford.edu/) and eligible materials may be checked out. [SearchWorks](https://searchworks.stanford.edu/) is available, but item status and availability information may not be up to date. Requests can be submitted, but materials may not be ready for use until after August 31. My Library Account will not be available until August 28. [More information](https://library.stanford.edu/news/major-system-upgrade-august-19-27)

**Comment by jcoyne** [comment]
Who will draft the text for this? @saseestone ?

**Comment by saseestone** [comment]
I've embedded the link in the text above, but the "More information" in each section should link to https://library.stanford.edu/news/major-system-upgrade-august-19-27

**Comment by saseestone** [comment]
links fixed @jcoyne
