### ISSUE TITLE
Timing the removal of alerts (related to folio migration)

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/global_alerts#54]
Related to https://github.com/sul-dlss/global_alerts/pull/50

We need to be careful about when we remove the global alerts on Monday. Instead of removing them automatically at midnight, the alerts outlined in https://github.com/sul-dlss/global_alerts/issues/49 should stay visible until we cut over to FOLIO. 

After we cut over, the alert should update to text outlined in https://github.com/sul-dlss/global_alerts/issues/53

**Comment by marlo-longley** [comment]
@saseestone if not midnight, what should the time be? I am not sure what "until we cut over to FOLIO" means, or if that exact timing remains to be seen.

**Comment by marlo-longley** [comment]
Update from Sarah --

For SW and Bento:
- [x] 1. now: We want to remove the midnight alert end date and convert the alerts to indefinitely on (needs manual removal).~~
   --- done via https://github.com/sul-dlss/global_alerts/pull/55

- [x] 2. after cutover: delete the indefinite alerts from above. Timing will be manual and Sarah will tell us it's time.

- [x] 3. after cutover: Update global alert text to what's in #53 (message that the cutover is completed) -- timing will be manual and @saseestone will tell us to merge https://github.com/sul-dlss/global_alerts/pull/56/files -- we will have to restart each app to see the alert reflected

For MyLibrary: 
- [x] 1. (now) Update the app code directly to say 28 not 27 (see that repo) on the outage page
  --- done via https://github.com/sul-dlss/mylibrary/pull/921

~~2. Remove the outage page after launch -- timing will be manual and @saseestone will tell us go~~
    -- This should happen automatically when mylibrary is able to connect to the Folio backend. We will need to swap the client in the app's settings and deploy. We will also need this Puppet PR to provide ENV vars: https://github.com/sul-dlss/puppet/pull/9820

- [x] 3. add new global alert to MyLibrary: this will happen via step 3 above (merging  https://github.com/sul-dlss/global_alerts/pull/56/files). Restart the app to reflect changes.
